export const industries = [
  'Technology',
  'Healthcare',
  'Finance',
  'Education',
  'Retail',
  'Manufacturing',
  'Hospitality',
  'Marketing',
  'Real Estate',
  'Entertainment',
  'Transportation',
  'Construction',
  'Energy',
  'Telecommunications',
  'Agriculture',
  'Media',
  'Non-profit',
  'Government',
  'Legal',
  'Consulting',
  'Other'
];

export const jobTypes = [
  'Full-time',
  'Part-time',
  'Contract',
  'Temporary',
  'Internship',
  'Freelance',
  'Apprenticeship'
];

export const technicalSkills = [
  'JavaScript',
  'Python',
  'Java',
  'C#',
  'C++',
  'Ruby',
  'PHP',
  'Swift',
  'Kotlin',
  'Go',
  'Rust',
  'TypeScript',
  'React',
  'Angular',
  'Vue.js',
  'Node.js',
  'Django',
  'Flask',
  'Spring',
  'Laravel',
  'Ruby on Rails',
  'SQL',
  'MongoDB',
  'PostgreSQL',
  'MySQL',
  'AWS',
  'Azure',
  'Google Cloud',
  'Docker',
  'Kubernetes',
  'Machine Learning',
  'Data Science',
  'Cybersecurity',
  'DevOps',
  'UI/UX Design',
  'iOS Development',
  'Android Development',
  'Blockchain',
  'Cloud Computing',
  'Big Data',
  'AI/ML',
  'Data Analysis',
  'Project Management',
  'Agile/Scrum',
  'Git',
  'CI/CD',
  'RESTful APIs',
  'GraphQL',
  'Microservices',
  'Linux'
];

export const softSkills = [
  'Communication',
  'Teamwork',
  'Problem Solving',
  'Time Management',
  'Critical Thinking',
  'Adaptability',
  'Creativity',
  'Work Ethic',
  'Interpersonal Skills',
  'Attention to Detail',
  'Leadership',
  'Responsibility',
  'Emotional Intelligence',
  'Conflict Resolution',
  'Decision Making',
  'Stress Management',
  'Organization',
  'Prioritization',
  'Negotiation',
  'Public Speaking'
];

export const languages = [
  'English',
  'Spanish',
  'French',
  'German',
  'Chinese (Mandarin)',
  'Hindi',
  'Arabic',
  'Portuguese',
  'Russian',
  'Japanese',
  'Korean',
  'Italian',
  'Dutch',
  'Swedish',
  'Turkish',
  'Polish',
  'Vietnamese',
  'Thai',
  'Greek',
  'Hebrew'
];
