interface ATSReportData {
  score: number;
  matchedKeywords: string[];
  missingKeywords: string[];
  jobTitle?: string;
  jobCompany?: string;
  analysisDate: string;
  recommendations: string[];
}

export const generateAtsReport = (data: ATSReportData) => {
  // Create a new window with the report content
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Pop-up was blocked. Please allow pop-ups for this site and try again.');
    return;
  }

  // Generate the report HTML
  const reportHTML = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>ATS Compatibility Report</title>
      <style>
        @media print {
          @page { size: A4; margin: 2cm; }
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #1e293b; }
          .header { text-align: center; margin-bottom: 2rem; }
          .title { 
            font-size: 24px; 
            color: #ec4899; /* Pink-500 */
            margin-bottom: 0.5rem;
          }
          .subtitle { 
            color: #64748b; /* Slate-500 */
            margin-bottom: 2rem;
          }
          .score-container { 
            text-align: center; 
            margin: 2rem 0;
          }
          .score-circle {
            display: inline-block;
            width: 120px;
            height: 120px;
            border-radius: 50%;
            border: 3px solid #ec4899; /* Pink-500 */
            text-align: center;
            line-height: 120px;
            font-size: 32px;
            font-weight: bold;
            margin-bottom: 1rem;
          }
          .section {
            margin: 2rem 0;
            page-break-inside: avoid;
          }
          .section-title {
            font-size: 18px;
            color: #1e293b;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 0.5rem;
            margin-bottom: 1rem;
          }
          .keyword {
            display: inline-block;
            background-color: #f3e8ff; /* Purple-100 */
            color: #7e22ce; /* Purple-700 */
            padding: 0.25rem 0.75rem;
            border-radius: 9999px;
            margin: 0.25rem;
            font-size: 0.875rem;
          }
          .missing-keyword {
            background-color: #fee2e2; /* Red-100 */
            color: #b91c1c; /* Red-700 */
          }
          .recommendation {
            margin-bottom: 0.75rem;
            padding-left: 1.5rem;
            position: relative;
          }
          .recommendation:before {
            content: '•';
            position: absolute;
            left: 0;
            color: #ec4899; /* Pink-500 */
          }
          .footer {
            margin-top: 3rem;
            padding-top: 1rem;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            font-size: 0.75rem;
            color: #64748b; /* Slate-500 */
          }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1 class="title">ATS Compatibility Report</h1>
        <p class="subtitle">Generated by Sebenza AI</p>
      </div>

      <div class="score-container">
        <div class="score-circle">${data.score}%</div>
        <div style="font-weight: bold; font-size: 1.125rem;">ATS Score</div>
      </div>

      ${data.jobTitle || data.jobCompany ? `
        <div class="section">
          <h2 class="section-title">Job Information</h2>
          ${data.jobTitle ? `<p><strong>Position:</strong> ${data.jobTitle}</p>` : ''}
          ${data.jobCompany ? `<p><strong>Company:</strong> ${data.jobCompany}</p>` : ''}
          <p><strong>Analysis Date:</strong> ${data.analysisDate}</p>
        </div>
      ` : ''}

      ${data.matchedKeywords.length > 0 ? `
        <div class="section">
          <h2 class="section-title">Matched Keywords</h2>
          <div>
            ${data.matchedKeywords.map(keyword => 
              `<span class="keyword">${keyword}</span>`
            ).join('')}
          </div>
        </div>
      ` : ''}

      ${data.missingKeywords.length > 0 ? `
        <div class="section">
          <h2 class="section-title">Missing Keywords</h2>
          <p>These keywords were found in the job description but not in your resume:</p>
          <div style="margin-top: 0.5rem;">
            ${data.missingKeywords.map(keyword => 
              `<span class="keyword missing-keyword">${keyword}</span>`
            ).join('')}
          </div>
        </div>
      ` : ''}

      ${data.recommendations.length > 0 ? `
        <div class="section">
          <h2 class="section-title">Recommendations</h2>
          <div>
            ${data.recommendations.map(rec => 
              `<div class="recommendation">${rec}</div>`
            ).join('')}
          </div>
        </div>
      ` : ''}

      <div class="footer">
        Generated by Sebenza AI • ${new Date().toLocaleDateString()}
      </div>

      <script>
        // Auto-print when the page loads
        window.onload = function() {
          setTimeout(function() {
            window.print();
            window.onafterprint = function() {
              window.close();
            };
          }, 500);
        };
      </script>
    </body>
    </html>
  `;

  // Write the HTML to the new window
  printWindow.document.write(reportHTML);
  printWindow.document.close();
};
